-- Bonus Coin Giveaway - Supabase PostgreSQL schema
-- Run this in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.settings (
  id integer primary key default 1 check (id = 1),
  welcome_heading text not null default 'Welcome to Bonus Coin Giveaway',
  welcome_message text not null default 'Complete the steps to enter the current giveaway.',
  security_message text not null default 'Your submitted information is secured and will not be publicly displayed.',
  primary_button_text text not null default 'Claim Reward',
  secondary_button_text text not null default 'View Rewards',
  updated_at timestamptz not null default now()
);

insert into public.settings (id)
values (1)
on conflict (id) do nothing;

create table if not exists public.giveaways (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null default '',
  reward_information text not null default '',
  image_url text,
  is_active boolean not null default false,
  start_date timestamptz,
  end_date timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date is null or start_date is null or end_date > start_date)
);

create unique index if not exists one_active_giveaway
on public.giveaways (is_active)
where is_active = true;

create index if not exists giveaways_dates_idx
on public.giveaways (start_date, end_date);

create table if not exists public.custom_fields (
  id uuid primary key default gen_random_uuid(),
  giveaway_id uuid not null references public.giveaways(id) on delete cascade,
  label text not null,
  placeholder text not null default '',
  field_type text not null default 'text'
    check (field_type in ('text','email','number','url','textarea')),
  required boolean not null default false,
  enabled boolean not null default true,
  copy_enabled boolean not null default false,
  display_order integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists custom_fields_giveaway_order_idx
on public.custom_fields (giveaway_id, display_order);

create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  giveaway_id uuid not null references public.giveaways(id) on delete restrict,
  submitted_data jsonb not null default '{}'::jsonb,
  eligibility_status text not null default 'eligible'
    check (eligibility_status in ('eligible','ineligible','pending')),
  created_at timestamptz not null default now()
);

create index if not exists submissions_giveaway_idx
on public.submissions (giveaway_id, created_at desc);

create index if not exists submissions_eligibility_idx
on public.submissions (giveaway_id, eligibility_status);

create table if not exists public.winners (
  id bigint generated by default as identity primary key,
  giveaway_id uuid not null unique references public.giveaways(id) on delete restrict,
  submission_id bigint not null unique references public.submissions(id) on delete restrict,
  selection_method text not null check (selection_method in ('random','manual')),
  selected_at timestamptz not null default now()
);

create index if not exists winners_giveaway_idx on public.winners (giveaway_id);

-- Keep updated_at current for settings/giveaways/custom_fields.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists settings_updated_at on public.settings;
create trigger settings_updated_at
before update on public.settings
for each row execute function public.set_updated_at();

drop trigger if exists giveaways_updated_at on public.giveaways;
create trigger giveaways_updated_at
before update on public.giveaways
for each row execute function public.set_updated_at();

drop trigger if exists custom_fields_updated_at on public.custom_fields;
create trigger custom_fields_updated_at
before update on public.custom_fields
for each row execute function public.set_updated_at();

-- RLS: browsers are not intended to access these tables directly.
-- The Express server uses the service-role key and performs authorization itself.
alter table public.settings enable row level security;
alter table public.giveaways enable row level security;
alter table public.custom_fields enable row level security;
alter table public.submissions enable row level security;
alter table public.winners enable row level security;

-- No anon/authenticated policies are created intentionally.
-- Service-role operations bypass RLS.
