let selectedGiveaway='', fieldData=[];
async function loadGiveaways(){const d=await api('/api/admin/giveaways');const s=document.getElementById('giveawaySelect');s.innerHTML=(d.giveaways||[]).map(g=>`<option value="${g.id}">${esc(g.title)}</option>`).join('');selectedGiveaway=s.value;if(selectedGiveaway)await loadFields()}
async function loadFields(){const d=await api('/api/admin/fields?giveaway_id='+encodeURIComponent(selectedGiveaway));fieldData=d.fields||[];render()}
function render(){const box=document.getElementById('fieldList');box.innerHTML=fieldData.map((f,i)=>`<div class="field-item" draggable="true" data-id="${f.id}"><span class="drag">☷</span><div class="field-info"><strong>${esc(f.label)}</strong><small>${esc(f.field_type)} · ${f.required?'required':'optional'} · ${f.enabled?'enabled':'disabled'}${f.copy_enabled?' · copy':''}</small></div><div class="field-actions"><button onclick="move(${i},-1)">↑</button><button onclick="move(${i},1)">↓</button><button onclick="editField('${f.id}')">Edit</button><button onclick="deleteField('${f.id}')">Delete</button></div></div>`).join('')||'<p class="muted">No custom fields yet. Add the first one.</p>'}
async function saveOrder(){try{await api('/api/admin/fields/reorder',{method:'PUT',headers:headers(),body:JSON.stringify({items:fieldData.map(f=>({id:f.id}))})})}catch(e){document.getElementById('flash').textContent=e.message}}
window.move=async(i,delta)=>{const j=i+delta;if(j<0||j>=fieldData.length)return;[fieldData[i],fieldData[j]]=[fieldData[j],fieldData[i]];render();await saveOrder()}
window.editField=id=>{const f=fieldData.find(x=>x.id===id);if(!f)return;openModal(f)}
window.deleteField=async id=>{if(!confirm('Delete this field? Existing submission data is not deleted, but this field will no longer be available for future forms.'))return;try{await api('/api/admin/fields/'+id,{method:'DELETE',headers:headers()});await loadFields()}catch(e){document.getElementById('flash').textContent=e.message}}
function openModal(f){document.getElementById('modal').classList.remove('hidden');document.getElementById('modalTitle').textContent=f?'Edit Field':'Add Field';document.getElementById('fieldId').value=f?.id||'';document.getElementById('label').value=f?.label||'';document.getElementById('placeholder').value=f?.placeholder||'';document.getElementById('field_type').value=f?.field_type||'text';document.getElementById('required').checked=!!f?.required;document.getElementById('enabled').checked=f?!!f.enabled:true;document.getElementById('copy_enabled').checked=!!f?.copy_enabled}
document.getElementById('addBtn').onclick=()=>openModal(null);document.getElementById('cancel').onclick=()=>document.getElementById('modal').classList.add('hidden');
document.getElementById('giveawaySelect').onchange=async e=>{selectedGiveaway=e.target.value;await loadFields()};
document.getElementById('fieldForm').onsubmit=async e=>{e.preventDefault();const id=document.getElementById('fieldId').value;const p={giveaway_id:selectedGiveaway,label:label.value,placeholder:placeholder.value,field_type:field_type.value,required:required.checked,enabled:enabled.checked,copy_enabled:copy_enabled.checked};try{if(id)await api('/api/admin/fields/'+id,{method:'PUT',headers:headers(),body:JSON.stringify(p)});else await api('/api/admin/fields',{method:'POST',headers:headers(),body:JSON.stringify(p)});document.getElementById('modal').classList.add('hidden');await loadFields()}catch(err){document.getElementById('flash').textContent=err.message}};(async()=>{try{await loadGiveaways()}catch(e){document.getElementById('flash').textContent=e.message}})();
